insert into roles (name) values 
('admin'),
('agent'),
('customer');

INSERT INTO property_types (id, name) VALUES
(1, 'Rumah'),
(2, 'Apartment'),
(3, 'Ruko'),
(4, 'Tanah');

INSERT INTO users (email, password, username, phone_number, role_id) 
VALUES 
('budi.agent@victoria.com', '$2a$10$Q4x/ZViUI0hQJLuVG7v1ZudEVPlImaIqyWf3bhYBZWAStjlyj6rUK', 'Budi Santoso', '081234567890', 2),
('siti.agent@victoria.com', '$2a$10$Q4x/ZViUI0hQJLuVG7v1ZudEVPlImaIqyWf3bhYBZWAStjlyj6rUK', 'Siti Aminah', '081298765432', 2),
('andi.agent@victoria.com', '$2a$10$Q4x/ZViUI0hQJLuVG7v1ZudEVPlImaIqyWf3bhYBZWAStjlyj6rUK', 'Andi Wijaya', '081311223344', 2);

-- Data dummy 15 properti dengan variasi lengkap
INSERT INTO properties (
    title,
    description,
    price,
    status,
    province,
    regency,
    district,
    address,
    building_area,
    land_area,
    electricity,
    water_source,
    bedrooms,
    bathrooms,
    floors,
    garage,
    carport,
    certificate,
    year_constructed,
    sale_type,
    created_at,
    property_type_id,
    agent_id
) VALUES
-- 1-3: Surabaya (Harga menengah-tinggi)
(
    'Rumah Minimalis Modern 2 Lantai',
    'Rumah minimalis modern di kawasan strategis, dekat sekolah dan pusat perbelanjaan. Desain interior modern, kondisi sangat terawat.',
    850000000,
    1,
    'Jawa Timur',
    'Surabaya',
    'Sukolilo',
    'Jl. Keputih No. 15',
    120,
    150,
    2200,
    1,
    3,
    2,
    2,
    1,
    1,
    'SHM',
    2018,
    'jual',
    NOW() - INTERVAL 5 DAY,
    1,
    1
),
(
    'Apartemen Fully Furnished Surabaya',
    'Apartemen siap huni, fully furnished dengan akses transportasi mudah. View city light, fasilitas lengkap: pool, gym, 24h security.',
    650000000,
    1,
    'Jawa Timur',
    'Surabaya',
    'Gubeng',
    'Jl. Gubeng No. 25',
    65,
    65,
    3500,
    2,
    2,
    1,
    1,
    0,
    0,
    'HGB',
    2020,
    'sewa',
    NOW() - INTERVAL 4 DAY,
    2,
    1
),
(
    'Ruko Strategis di Surabaya Barat',
    'Ruko 2 lantai di jalur komersial strategis, cocok untuk usaha kuliner, retail, atau kantor. Daya listrik besar, akses parkir luas.',
    1200000000,
    1,
    'Jawa Timur',
    'Surabaya',
    'Rungkut',
    'Jl. Rungkut Industri No. 45',
    90,
    120,
    22000,
    1,
    0,
    2,
    2,
    0,
    2,
    'SHM',
    2015,
    'jual',
    NOW() - INTERVAL 3 DAY,
    3,
    2
),
-- 4-6: Jakarta Selatan (Premium)
(
    'Apartemen Mewah SCBD Jakarta',
    'Apartemen premium di kawasan SCBD, view langsung ke taman, akses ke mall, fitness center. Interior desain oleh arsitek ternama.',
    3500000000,
    1,
    'DKI Jakarta',
    'Jakarta Selatan',
    'Setiabudi',
    'Jl. HR Rasuna Said Kav. 10',
    85,
    85,
    4400,
    2,
    2,
    2,
    1,
    0,
    0,
    'HGB',
    2022,
    'jual',
    NOW() - INTERVAL 2 DAY,
    2,
    2
),
(
    'Rumah Mewah di Pondok Indah',
    'Rumah mewah dengan kolam renang pribadi, garden landscape profesional, smart home system, CCTV 24 jam, 4 kamar tidur suite.',
    8500000000,
    1,
    'DKI Jakarta',
    'Jakarta Selatan',
    'Kebayoran Lama',
    'Jl. Metro Pondok Indah',
    450,
    800,
    22000,
    1,
    4,
    5,
    3,
    3,
    3,
    'SHM',
    2020,
    'jual',
    NOW() - INTERVAL 6 DAY,
    1,
    2
),
(
    'Kontrakan Murah Jagakarsa',
    'Kontrakan siap huni, cocok untuk mahasiswa/karyawan, dekat kampus dan transportasi umum. Air PAM, listrik token.',
    2500000,
    1,
    'DKI Jakarta',
    'Jakarta Selatan',
    'Jagakarsa',
    'Jl. Lenteng Agung No. 12',
    24,
    30,
    1300,
    2,
    1,
    1,
    1,
    0,
    0,
    'SHGB',
    2010,
    'sewa',
    NOW() - INTERVAL 7 DAY,
    1,
    3
),
-- 7-9: Bandung (Wisata & Hunian)
(
    'Rumah Klasik Bandung dengan Halaman Luas',
    'Rumah klasik bergaya kolonial dengan halaman luas, taman asri, cocok untuk keluarga besar. Lokasi tenang dekat Dago.',
    1250000000,
    1,
    'Jawa Barat',
    'Bandung',
    'Cidadap',
    'Jl. Ciumbuleuit No. 88',
    180,
    300,
    4400,
    1,
    4,
    3,
    2,
    2,
    2,
    'SHM',
    2015,
    'jual',
    NOW() - INTERVAL 8 DAY,
    1,
    3
),
(
    'Guest House di Kawasan Wisata',
    'Guest house dengan 5 kamar, cocok untuk bisnis homestay/villa. Lokasi strategis dekat Braga dan alun-alun Bandung.',
    1800000000,
    1,
    'Jawa Barat',
    'Bandung',
    'Sumur Bandung',
    'Jl. Braga No. 30',
    200,
    250,
    22000,
    1,
    5,
    4,
    2,
    2,
    2,
    'SHM',
    2018,
    'jual',
    NOW() - INTERVAL 9 DAY,
    1,
    1
),
(
    'Apartemen Studio di Bandung Timur',
    'Apartemen studio minimalis, cocok untuk single atau pasangan. Fasilitas: wifi, AC, dapur kecil, dekat kampus ITB.',
    350000000,
    1,
    'Jawa Barat',
    'Bandung',
    'Bandung Wetan',
    'Jl. Ganesha No. 7',
    30,
    30,
    2200,
    2,
    1,
    1,
    1,
    0,
    0,
    'HGB',
    2021,
    'sewa',
    NOW() - INTERVAL 1 DAY,
    2,
    2
),
-- 10-12: Bali (Wisata & Investasi)
(
    'Villa Luxury di Seminyak Bali',
    'Villa mewah dengan private pool, butler service, ocean view. Cocok untuk investasi villa atau residence pribadi.',
    5500000000,
    1,
    'Bali',
    'Badung',
    'Kuta Utara',
    'Jl. Petitenget No. 100',
    350,
    600,
    44000,
    1,
    4,
    4,
    2,
    2,
    2,
    'SHM',
    2021,
    'jual',
    NOW() - INTERVAL 10 DAY,
    1,
    3
),
(
    'Tanah Kavling di Canggu',
    'Tanah siap bangun di kawasan premium Canggu, dekat pantai, cocok untuk villa atau cafe. Sertifikat lengkap, IMB tersedia.',
    1800000000,
    1,
    'Bali',
    'Badung',
    'Kuta Selatan',
    'Jl. Pantai Batu Bolong',
    0,
    400,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    'SHM',
    0,
    'jual',
    NOW() - INTERVAL 11 DAY,
    4,
    1
),
(
    'Kost Eksklusif di Denpasar',
    'Kost eksklusif putri, 10 kamar dengan AC, wifi, cleaning service. Cocok untuk investasi pasif income.',
    3200000000,
    1,
    'Bali',
    'Denpasar',
    'Denpasar Barat',
    'Jl. Teuku Umar No. 45',
    300,
    400,
    33000,
    1,
    10,
    8,
    2,
    1,
    2,
    'SHM',
    2019,
    'jual',
    NOW() - INTERVAL 12 DAY,
    1,
    2
),
-- 13-15: Lainnya (Variasi)
(
    'Rumah Subsidi Type 36',
    'Rumah subsidi type 36, cocok untuk keluarga muda. Lingkungan asri, dekat pasar dan sekolah.',
    250000000,
    1,
    'Jawa Tengah',
    'Semarang',
    'Tembalang',
    'Jl. Perumahan Graha Indah Blok A1',
    36,
    60,
    2200,
    1,
    2,
    1,
    1,
    1,
    0,
    'SHM',
    2022,
    'jual',
    NOW() - INTERVAL 13 DAY,
    1,
    3
),
(
    'Kios di Pasar Tradisional',
    'Kios strategis di pasar tradisional, laris, cocok untuk usaha sembako atau makanan. Sudah ada pelanggan tetap.',
    450000000,
    1,
    'Jawa Barat',
    'Bogor',
    'Bogor Tengah',
    'Pasar Anyar Bogor Blok C No. 12',
    25,
    25,
    4500,
    1,
    0,
    1,
    1,
    0,
    0,
    'HGB',
    2010,
    'jual',
    NOW() - INTERVAL 14 DAY,
    3,
    1
),
(
    'Apartemen View Gunung di Malang',
    'Apartemen dengan view gunung, udara sejuk, cocok untuk investasi atau tempat tinggal. Dekat universitas ternama.',
    425000000,
    1,
    'Jawa Timur',
    'Malang',
    'Klojen',
    'Jl. Besar Ijen No. 25',
    45,
    45,
    2200,
    2,
    1,
    1,
    1,
    0,
    0,
    'HGB',
    2020,
    'sewa',
    NOW() - INTERVAL 0 DAY,
    2,
    2
);

insert into users (email, password, username, phone_number, role_id) values 
('admin@admin.com', '$2a$10$Q4x/ZViUI0hQJLuVG7v1ZudEVPlImaIqyWf3bhYBZWAStjlyj6rUK', 'adminuser', '1234567890', 1);
