insert into roles (name) values 
('admin'),
('agent'),
('customer');

INSERT INTO property_types (id, name) VALUES
(1, 'House'),
(2, 'Apartment'),
(3, 'Land');

INSERT INTO properties (
    title,
    description,
    price,
    status,
    province,
    regency,
    district,
    address,
    building_area,
    land_area,
    electricity,
    water_source,
    bedrooms,
    bathrooms,
    floors,
    garage,
    carport,
    certificate,
    year_constructed,
    created_at,
    property_type_id,
    agent_id
) VALUES
(
    'Rumah Minimalis Modern 2 Lantai',
    'Rumah minimalis modern di kawasan strategis, dekat sekolah dan pusat perbelanjaan.',
    850000000,
    1,
    'Jawa Timur',
    'Surabaya',
    'Sukolilo',
    'Jl. Keputih No. 15',
    120,
    150,
    2200,
    1,
    3,
    2,
    2,
    1,
    1,
    'SHM',
    2018,
    NOW(),
    1,
    11
),
(
    'Apartemen Fully Furnished',
    'Apartemen siap huni, fully furnished dengan akses transportasi mudah.',
    650000000,
    1,
    'DKI Jakarta',
    'Jakarta Selatan',
    'Setiabudi',
    'Jl. HR Rasuna Said Kav. 10',
    65,
    65,
    3500,
    2,
    2,
    1,
    1,
    0,
    0,
    'HGB',
    2020,
    NOW(),
    2,
    11
),
(
    'Rumah Klasik dengan Halaman Luas',
    'Rumah klasik dengan halaman luas, cocok untuk keluarga besar.',
    1250000000,
    1,
    'Jawa Barat',
    'Bandung',
    'Cidadap',
    'Jl. Ciumbuleuit No. 88',
    180,
    300,
    4400,
    1,
    4,
    3,
    2,
    2,
    2,
    'SHM',
    2015,
    NOW(),
    1,
    11
);

insert into users (email, password, username, phone_number, role_id) values 
('admin@admin.com', '$2a$10$UBCeBHKUVi8YyUvPlUVq/O12Cgju3M/XweUgIuQJ9mf72nf2kvzei', 'adminuser', '1234567890', 1);
